export const FETCH_PIZZA_LIST_REQUESTED = 'FETCH_PIZZA_LIST_REQUESTED';
export const FETCH_PIZZA_LIST_SUCCEEDED = 'FETCH_PIZZA_LIST_SUCCEEDED';
export const FETCH_PIZZA_LIST_FAILED = 'FETCH_PIZZA_LIST_FAILED';

export const fetchPizzasList = () => ({ type: FETCH_PIZZA_LIST_REQUESTED });
