export const SECONDARY_NAV_ACTIVATE_REQUESTED = 'SECONDARY_NAV_ACTIVATE_REQUESTED';
export const SECONDARY_NAV_ACTIVATE_SUCCEEDED = 'SECONDARY_NAV_ACTIVATE_SUCCEEDED';
export const SECONDARY_NAV_ACTIVATE_FAILED = 'SECONDARY_NAV_ACTIVATE_FAILED';

export const openSecondaryNav = payload => ({type: 'SECONDARY_NAV_ACTIVATE_REQUESTED', payload});
